name: yq-yaml-parser
description: Convert a yaml properties to GitHub Actions output
author: BetaOn Actions

inputs:
  file-path:
    description: "Path to the yaml file to read"
    required: true

runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_YAML_FILE_PATH: "${{ inputs.file-path }}"
