name: yq yaml parser
description: Convert a yaml to GitHub Actions outputs
author: BetaOn Actions

branding:
  icon: code
  color: blue

inputs:
  file-path:
    description: Path to the yaml file to read
    required: true
  filtering-keys:
    description: |
      Read using specific filter
        filtering-keys: |          
          key1_nested
          key2_nested_0      
      If not provided, all keys will be read
    required: false
  renaming-outputs:
    description: |      
      Can be used to rename the default output name
        renaming-outputs: |
          key1_nested=my_output
          key2_nested_0=my_output_2                      
    required: false    

runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_YAML_FILE_PATH: "${{ inputs.file-path }}"
    INPUT_YAML_FILTERING_KEYS: "${{ inputs.filtering-keys }}"
    INPUT_YAML_RENAMING_OUTPUTS: "${{ inputs.renaming-outputs }}"
