name: yq-yaml-parser
description: Convert a yaml to GitHub Actions outputs
author: BetaOn Actions

branding:
  icon: code
  color: blue

inputs:
  file-path:
    description: "Path to the yaml file to read"
    required: true

runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_YAML_FILE_PATH: "${{ inputs.file-path }}"
