name: Continuous Integration - Test Action

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - feature/check-debug

permissions:
  contents: read

jobs:
  test-action-outputs:
    name: Test Action Outputs
    uses: ./.github/workflows/ci-test-outputs.yml

  test-action-filters:
    name: Test Action Filters
    uses: ./.github/workflows/ci-test-filters.yml    
